name: webauthnexample
description: Demonstrates how to use the webauthn package

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webauthn:
    path: '../'
  sqflite_common_ffi: ^2.2.0+1
  sqflite: ^2.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
