targets:
  $default:
    sources:
      exclude:
       - test-service/**
       - example/**
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/src/models/{{}}.dart': 'lib/src/models/generated/{{}}.g.dart'
            '^lib/src/db/{{}}.dart': 'lib/src/db/generated/{{}}.g.dart'