name: webauthn
description: A plugin implementing the WebAuthn authenticator model for generating Public Key Credentials
version: 0.0.2
homepage:
repository: https://github.com/flutter-institute/webauthn
issue_tracker: https://github.com/flutter-institute/webauthn/issues
platforms:
  android:
  ios:
  windows:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cbor: ^5.1.0
  crypto_keys: ^0.3.0
  equatable: ^2.0.3
  flutter_secure_storage: ^5.1.0
  json_annotation: ^4.6.0
  local_auth: ^2.1.2
  path_provider: ^2.0.11
  sqflite: ^2.0.3+1
  path: ^1.8.1
  logger: ^1.1.0
  crypto: ^3.0.2
  hex: ^0.2.0
  analyzer: ^4.6.0
  local_auth_android: ^1.0.11
  local_auth_ios: ^1.0.9
  local_auth_windows: ^1.0.3
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mockito: 5.2.0 # Mockito 5.3.0 is incompatible with isar. They require different version of the analyzer. Mockito 5.2.0 solves this issue.
  sqflite_common_ffi: ^2.1.1+1

flutter:
