name: webauthn
description: A plugin implementing the WebAuthn authenticator model for generating Public Key Credentials
version: 0.2.5
homepage:
repository: https://github.com/flutter-institute/webauthn
issue_tracker: https://github.com/flutter-institute/webauthn/issues
platforms:
  android:
  ios:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  byte_extensions: ^0.0.3
  cbor: ^6.3.0
  collection: ^1.18.0
  crypto: ^3.0.6
  crypto_keys: ^0.3.0+1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  hex: ^0.2.0
  json_annotation: ^4.8.1
  local_auth: ^2.3.0
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  precis: ^0.0.3
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.3
  mockito: ^5.3.2
  sqflite_common_ffi: ^2.3.4+4

flutter:
